In [1]:
import numpy as np
import math
import re
from collections import Counter
from functools import cmp_to_key

In [82]:
with open("09-input", "r") as file:
    lines = file.readlines()
data_raw = [line.replace("\n", "") for line in lines]
data_raw = "\n".join(data_raw)
data_raw

'21 32 43 50 52 63 128 354 980 2536 6198 14571 33400 75257 167315 367301 795349 1696172 3558635 7344376 14925482\n29 42 53 56 39 -4 -34 127 1001 3868 11543 29740 69331 149906 305152 590695 1095189 1955590 3377721 5663416 9245727\n4 13 31 69 161 382 885 1967 4170 8430 16326 30587 56237 103154 191459 362164 697242 1356689 2647559 5156471 10012899\n8 14 21 35 62 107 169 235 286 352 697 2286 7805 23735 64493 160875 377960 854409 1890137 4141400 9048308\n-2 0 12 46 132 343 844 1984 4452 9527 19484 38295 72924 135831 249908 458206 842858 1561142 2912508 5459800 10242444\n16 42 79 127 186 256 337 429 532 646 771 907 1054 1212 1381 1561 1752 1954 2167 2391 2626\n-4 9 49 128 256 441 689 1004 1388 1841 2361 2944 3584 4273 5001 5756 6524 7289 8033 8736 9376\n6 15 41 99 222 476 978 1915 3562 6297 10611 17111 26514 39630 57332 80511 110014 146563 190653 242427 301526\n17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57\n11 16 34 80 183 405 879 1875 3912 7964 15871 31182 60871 118775 2323

In [27]:
test_data_raw = """0 3 6 9 12 15
1 3 6 10 15 21
10 13 16 21 30 45"""

def preprocess_data (data):
    history = []
    for row in data.split("\n"):
        history.append(np.array([int(a) for a in row.split(" ")], dtype=np.int64))

    return history

test_data = preprocess_data(test_data_raw)
test_data

[array([ 0,  3,  6,  9, 12, 15], dtype=int64),
 array([ 1,  3,  6, 10, 15, 21], dtype=int64),
 array([10, 13, 16, 21, 30, 45], dtype=int64)]

In [59]:
data = preprocess_data(data_raw)
data

[array([      21,       32,       43,       50,       52,       63,
             128,      354,      980,     2536,     6198,    14571,
           33400,    75257,   167315,   367301,   795349,  1696172,
         3558635,  7344376, 14925482], dtype=int64),
 array([     29,      42,      53,      56,      39,      -4,     -34,
            127,    1001,    3868,   11543,   29740,   69331,  149906,
         305152,  590695, 1095189, 1955590, 3377721, 5663416, 9245727],
       dtype=int64),
 array([       4,       13,       31,       69,      161,      382,
             885,     1967,     4170,     8430,    16326,    30587,
           56237,   103154,   191459,   362164,   697242,  1356689,
         2647559,  5156471, 10012899], dtype=int64),
 array([      8,      14,      21,      35,      62,     107,     169,
            235,     286,     352,     697,    2286,    7805,   23735,
          64493,  160875,  377960,  854409, 1890137, 4141400, 9048308],
       dtype=int64),
 array([      -2

In [105]:

def solution (data):
    extrapolation = np.array([], dtype=np.int64)
    for idx, row in enumerate(data):
        current = row
        last_elements = current[-1:]
        while np.sum(np.abs(current)) != 0:
            current = current[1:] - current[:-1]

            last_elements = np.append(last_elements, current[-1]) 

        extrapolation = np.append(extrapolation, np.sum(last_elements))

    return extrapolation


winnings = solution(data)
# winnings = solution(test_data)
# display(winnings)

# display(winnings)
print(np.sum(winnings))

2038472161


In [110]:
def solution (data):
    extrapolation = np.array([], dtype=np.int64)
    solution = 0
    for idx, row in enumerate(data):
        history = [row]
        current = row
        while np.sum(np.abs(current)) != 0:
            current = current[1:] - current[:-1]
            history += [current]

        extrapolation_steps = []
        zero_element = 0
        for step in reversed(history):
            zero_element = step[0] - zero_element 
            extrapolation_steps += [np.append(np.array(zero_element), step)]

        solution += zero_element
        

    return solution


winnings = solution(data)
# winnings = solution(test_data)
# display(winnings)

display(winnings)


1091